version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo install

  pre_build:
    commands:
      - echo pre_build

  build:
    commands:
      - echo build

  post_build:
    commands:
      - echo post_build
       - printf '[{"name":"your.task.definition.name","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
  
  artifacts:
    files: imagedefinitions.json
