version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo install

  pre_build:
    commands:
      - echo pre_build

  build:
    commands:
      - echo build

  post_build:
    commands:
      - echo post_build
       - printf '[{"name":"your.task.definition.name","imageUri":"%s"}]' 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest > imagedefinitions.json
 
