version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --no-include-email --region ap-northeast-2  | docker login --username AWS --password-stdin 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker test image...
      - docker build -t ample-im .
      - docker tag ample-im:latest 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im-test-repository:latest
      - docker push 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest

