version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
      - npm install yarn
  build:
    commands:
      - docker build -t ample-im .
  post_build:
    commands:
      - docker tag ample-im:latest 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest
      - docker push 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest
          
