version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws --version
      - npm install yarn
  build:
    commands:
      - docker build -t ample-im .
  post_build:
    commands:
      - docker tag ample-im:latest 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest
      - docker push 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ample-im-container","imageUri":"%s"}]' 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
