on:
  push:
    branches: [master]

name: AWS ECR push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ample-im
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to ECR 
          docker build -t ample-im .
          
      - name: docker login
        run: aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com
 
      - name: tag image
        run: |
          docker tag ample-im:latest 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest
          
      - name: push image
        run: |
          echo "Pushing image to ECR..."
          docker push 080359934252.dkr.ecr.ap-northeast-2.amazonaws.com/ample-im:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
